# Generated by Django 2.0.1 on 2018-01-27 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EncryptDecrypt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symmetric_asymmetric', models.CharField(choices=[('symmetric', 'Symmetric Algo'), ('asymmetric', 'ASymmetric Algo')], default='symmetric', max_length=2)),
                ('symmetric_tech', models.CharField(choices=[('ceaser cipher', 'Ceaser Ciper')], default='ceaser cipher', max_length=2)),
                ('asymmetric_tech', models.CharField(choices=[('des', 'des 8 bit  ')], default='des', max_length=1)),
                ('message', models.CharField(max_length=100)),
                ('key', models.IntegerField()),
            ],
        ),
    ]
