# Generated by Django 2.0.2 on 2018-02-21 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cryptoclient', '0003_auto_20180127_1257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='encryptdecrypt',
            name='key',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='encryptdecrypt',
            name='symmetric_tech',
            field=models.CharField(choices=[('ceaser cipher', 'Ceaser Ciper'), ('play fair', 'Play Fair'), ('hill cipher', 'Hill Cipher')], default='', max_length=100),
        ),
    ]
